config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lists do
    resources :movies do
      post 'complete' => 'movies#change_status'
    end
  end

  get '/completed_movies' => 'movies#completed_movies'

  root 'home#index'
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :listings, dependent: :destroy
  has_many :movies, through: :listings

  validates :title, presence: true
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list, only: %i[edit update destroy]

  def index
    @pagy, @lists = pagy(current_user.lists.all)
    @list = current_user.lists.new
  end

  def show
    @list = List.find(params[:id])
    @pagy_movies_all, @movies_all = pagy(@list.movies,
                                         page_param: :page_movies_all,
                                         params: { active_tab: 'movies_all' })
    @pagy_movies_completed, @movies_completed = pagy(@movies_all.completed,
                                                     page_param: :page_movies_completed,
                                                     params: { active_tab: 'movies_completed' })
    @pagy_movies_in_progress, @movies_in_progress = pagy(@movies_all.active,
                                                         page_param: :page_movies_in_progress,
                                                         params: { active_tab: 'movies_in_progress' })
  end

  def create
    @list = current_user.lists.create(list_params)

    redirect_to @list if @list.save
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to @list
    else
      render 'edit'
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:title)
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<div class="modal fade" id="new-list" tabindex="-1" role="dialog" aria-labelledby="new-list-title" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="new-list-title">Create a new list</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
     <div class="modal-body">
        <%= form_with model: @list do |f| %>
        <div class="form-group">
          <%= f.label :title, class: "col-form-label" %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit "Create", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/_list.html.erb
<li class="list-group-item p-0">
  <%= link_to(list_path(list), class: "p-3 d-flex justify-content-between align-items-center list-group-item-action") do %>
    <span><%= list.title %></span>
    <span class="badge badge-info badge-pill"><%= list.movies.size %></span>
  <% end %>
</li>

app/views/lists/index.html.erb
<div class="mb-3 d-flex justify-content-between align-items-center">
  <%= link_to 'Back', root_path, class: "btn btn-outline-secondary" %>
  <button type="button" class="btn btn-outline-secondary" data-toggle="modal" data-target="#new-list">New list</button>
  <%= render 'form', path: {controller: "lists", action: "create"} %>
</div>

<ul class="list-group">
  <% @lists.each do |list| %>
    <%= render list %>
  <% end %>
</ul>

app/views/lists/old_show.html.erb
<div class="mb-3 d-flex justify-content-between align-items-center">
  <%= link_to 'Back', lists_path, class: "btn btn-outline-secondary" %>
  <%= link_to 'Delete the list', list_path,
                             method: :delete,
                             data: { confirm: 'Are you sure?' },
                             class: "btn btn-outline-dark" %>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Original Title</th>
      <th scope="col">Russian Title</th>
      <th scope="col">Release Year</th>
      <th scope="col">Genre</th>
      <th scope="col">Country</th>
      <th scope="col">Rating</th>
      <th scope="col">URL</th>
    </tr>
  </thead>
  <tbody>
    <% @list.movies.each_with_index do |movie, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td><%= movie.original_title %></td>
        <td><%= movie.rus_title %></td>
        <td><%= movie.release_year %></td>
        <td><%= movie.genre %></td>
        <td><%= movie.country %></td>
        <td><%= movie.rating %></td>
        <td><a href="<%= movie.url %>" target="_blank">Go to <%= movie.source%></a></td>
        <td>
          <%= link_to 'Complete', list_movie_complete_path(@list, movie), method: :post %>
        </td>
        <td>
          <%= link_to 'Remove', list_movie_path(@list, movie), method: :delete %>
        </td>
      <tr>
    <% end %>
  </tbody>
</table>

<%= render 'movies/form' %>

app/views/lists/show.html.erb
<div class="mb-3 d-flex justify-content-between align-items-center">
  <%= link_to 'Back', lists_path, class: "btn btn-outline-secondary" %>
  <%= link_to 'Delete the list', list_path,
                             method: :delete,
                             data: { confirm: 'Are you sure?' },
                             class: "btn btn-outline-dark" %>
</div>

<nav>
  <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item">
      <a class="nav-link <%= 'active' unless params[:active_tab] == 'movies_in_progress' || params[:active_tab] == 'movies_completed' %>" id="pills-movies-all-tab" data-toggle="tab" href="#pills-movies-all" role="tab" aria-controls="pills-movies-all" aria-selected="true">All</a>
    </li>
    <li class="nav-item">
      <a class="nav-link <%= 'active' if params[:active_tab] == 'movies_in_progress'%>" id="pills-movies-in-progress-tab" data-toggle="tab" href="#pills-movies-in-progress" role="tab" aria-controls="pills-movies-in-progress" aria-selected="false">In Progress</a>
    </li>
    <li class="nav-item">
      <a class="nav-link <%= 'active' if params[:active_tab] == 'movies_completed'%>" id="pills-movies-completed-tab" data-toggle="tab" href="#pills-movies-completed" role="tab" aria-controls="pills-movies-completed" aria-selected="false">Completed</a>
    </li>
  </div>
</nav>
<div class="tab-content col-12" id="pills-tabContent">
  <div class="tab-pane fade <%= 'show active' unless params[:active_tab] == 'movies_in_progress' || params[:active_tab] == 'movies_completed' %>" id="pills-movies-all" role="tabpanel" aria-labelledby="pills-movies-all-tab">
    <%= render 'movies/movies_all'%>
  </div>
  <div class="tab-pane fade <%= 'show active' if params[:active_tab] == 'movies_in_progress'%>" id="pills-movies-in-progress" role="tabpanel" aria-labelledby="pills-movies-in-progress-tab">
    <%= render 'movies/movies_in_progress'%>
  </div>
  <div class="tab-pane fade <%= 'show active' if params[:active_tab] == 'movies_completed'%>" id="pills-movies-completed" role="tabpanel" aria-labelledby="pills-movies-completed-tab">
    <%= render 'movies/movies_completed'%>
  </div>
  <%= render 'movies/form'%>
</div>